name: Publish Wiki

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Provide a reason to manually compile wiki'
        type: string
        required: true

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/checkout@master
      - name: Typedoc Wiki
        uses: TypeStrong/typedoc-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: OrlovM/Wiki-Action@v1
        with:
          path: "docs"
          token: ${{ secrets.GITHUB_TOKEN }}
