name: Publish Wiki

on: push
  # release:
  #   types: [published]

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/checkout@master
        name: Checkout
      - uses: TypeStrong/typedoc-action@v1
        name: TypeDoc Gen
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: OrlovM/Wiki-Action@v1
        name: Wiki Push
        with:
          path: "docs"
          token: ${{ secrets.GITHUB_TOKEN }}
